### ISSUE TITLE
Desiderate: offer `fullref`

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#16] opened 2024-01-08 17:54 UTC
In the KWIC-view: because we do not offer the user with any option to edit their "View Options" - i.e. selecting e.g. what meta-data-fields should be displayed, it would be very conventient to offer them an easy way to just see **all** the metadata. 

There is a simple method `fullref` which fetches the "full ref" 
https://www.sketchengine.eu/apidoc/#/Corpus%20Search/get_search_fullref

In the NoSke the results of fullref are presented in a way, that it allows to edit the view-options. 
This is nice, but a simple display without the checkboxes etc. would also do for a start

![image](https://github.com/acdh-oeaw/corpsum-ts/assets/8236186/b6692c14-36e4-4f34-b883-7325422daca5)

**Comment by ctot-nondef** [comment] 2024-03-05 15:03
dupe of #17

**Closed by ctot-nondef** 2024-03-05 15:03 UTC
Labels: enhancement
